### ISSUE TITLE
removeHoles Bug

### ISSUE THREAD

**Issue by ghost** [leverdeterre/JMHoledView#4]
Hi, 
- (void)removeHoles
  {
  [self.holes removeAllObjects];
  [self removeCustomViews];
  [self setNeedsDisplay];
  }

Change To:
- (void)removeHoles
  {
  [self removeCustomViews];
  [self.holes removeAllObjects];
  [self setNeedsDisplay];
  }

**Comment by leverdeterre** [comment]
Thanks, 
I have report this fix manually.
don't hesitate to do a pull request :)
